/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContentOfTheSites: typeof import('./components/ContentOfTheSites.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ListOfItems: typeof import('./components/ListOfItems.vue')['default']
    MediaGallery: typeof import('./components/MediaGallery.vue')['default']
    MediaNavigationMenu: typeof import('./components/MediaNavigationMenu.vue')['default']
    NavigationMenu: typeof import('./components/NavigationMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}
